language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  global:
    - setup=basic

# Optimize the build since we are `composer installing` for each supported
# Laravel versions (see composer.json, under scripts sections).
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer config discard-changes true
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist --verbose
